import Head from "next/head";
import Draggable from "react-draggable";
import { useState, useEffect } from "react";

export default function Home() {
  const [value, setValue] = useState("");
  const [list, setList] = useState([]);
  const submitHandler = (e) => {
    e.preventDefault();

   
    setList([...list, value]);
    setValue('');

  };
  useEffect(() => {}, [value, list]);
  const valueHandler = (e) => {
    e.preventDefault();
    setValue(e.target.value);
  };
  return (
    <div>
      <Head>
        <title>Draggable List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex  w-screen h-screen">
        
        <div className=" flex flex-col w-1/2 h-screen bg-gray-200 justify-evenly mx-auto align-middle p-10">
        <h1>Draggable list creator</h1>
          <form onSubmit={submitHandler}>
            {" "}
            <input
              placeholder="list items"
              type="text"
              value={value}
              onChange={valueHandler}
              className="w-1/2 p-3 mt-1 text-sm border-2 border-gray-200 rounded"
            />
            <input
              type="submit"
              className="inline-block px-12 py-3 text-sm font-medium text-white bg-indigo-600 border border-indigo-600 rounded active:text-indigo-500 hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring"
            disabled = {value.length === 0}
            />
          </form>
          <div className="flex flex-col">
          {list.length < 1
            ? ""
            : list.map((item, index) => {
                return <Draggable  key={index}>
                  <button
                    className="bg-black w-1/4 shadow-lg text-white border-8"
                   
                  >
                    {item}
                  </button>
                </Draggable>;
              })}
          </div>
          
        </div>
        <div className="w-1/2 h-screen bg-red-200">
          <h1 className="m-10">Dragged lists</h1>
        </div>
      </div>
    </div>
  );
}
